'''String selectors for scraping immobiliare website'''
from ...utils.selectors import XPATH_ONSALE_LIST_IMMOBILIARE

XPATH_ONSALE_LIST = selectors.XPATH_ONSALE_LIST_IMMOBILIARE 
XPATH_PRICE = selectors.XPATH_PRICE_IMMOBILIARE 
XPATH_N_OF_ROOMS = selectors.XPATH_N_OF_ROOMS_IMMOBILIARE
XPATH_LIVING_SPACE = selectors.XPATH_LIVING_SPACE_IMMOBILIARE 
XPATH_BATHROOMS = selectors.XPATH_BATHROOMS_IMMOBILIARE 
XPATH_AGENCY = selectors.XPATH_AGENCY_IMMOBILIARE 
XPATH_TITLE = selectors.XPATH_TITLE_IMMOBILIARE 
XPATH_HREF = selectors.XPATH_HREF_IMMOBILIARE 

